import { test, expect } from '@playwright/test';

test('desktop keeps controls beside the five-year projection and changes it in place', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/fiscal-space');
  const heading = page.getByRole('heading', { name: '5年間の状態遷移', exact: true });
  await heading.scrollIntoViewIfNeeded();
  const panel = page.getByRole('region', { name: '政策の操作パネル' });
  const bounds = (await panel.boundingBox())!;
  expect(bounds.y).toBeGreaterThanOrEqual(0);
  expect(bounds.y + bounds.height).toBeLessThanOrEqual(1000);
  // 入力で上部の表示（公共資本の便益など）が伸縮しても、見出しの画面内位置が保たれること（スクロール固定ではなく「その場で変わる」ことを検証）。
  const headingTop = async () => Math.round((await heading.boundingBox())!.y);
  const topBefore = await headingTop();
  const graph = page.getByRole('region', { name: '政策なしとの差のグラフ', exact: true }).locator('polyline').first();
  const before = await graph.getAttribute('points');
  await page.getByLabel('公共投資・数値で入力', { exact: true }).fill('10');
  await expect.poll(headingTop).toBe(topBefore);
  await expect(graph).not.toHaveAttribute('points', before!);
  await expect(heading).toBeInViewport();
  // 「詳細な条件」は既定で閉じているため、ダイアログの開閉ボタンを表示させる。
  await panel.getByText('詳細な条件', { exact: true }).click();
  await panel.getByRole('button', { name: '経済状態・評価条件を変える', exact: true }).click();
  const economy = page.getByRole('dialog', { name: '経済状態・評価条件', exact: true });
  await expect(economy).toBeVisible();
  await page.getByLabel('制約の評価期間', { exact: true }).selectOption('3');
  await economy.getByRole('button', { name: '設定を閉じて結果を見る', exact: true }).click();
  await expect(panel.getByRole('button', { name: '経済状態・評価条件を変える', exact: true })).toBeFocused();
  await expect(page.getByTestId('horizon-results').getByRole('heading')).toHaveText('3年目の結果（試算）');
  await expect(heading).toBeInViewport();
});

test('mobile opens controls and model dialog without leaving the projection', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/fiscal-space');
  const heading = page.getByRole('heading', { name: '5年間の状態遷移', exact: true });
  await heading.scrollIntoViewIfNeeded();
  const headingTop = async () => Math.round((await heading.boundingBox())!.y);
  const topBefore = await headingTop();
  await page.getByRole('button', { name: /^政策を調整/ }).click();
  const panel = page.getByRole('region', { name: '政策の操作パネル' });
  await expect(panel).toBeInViewport();
  const economyOpener = panel.getByRole('button', { name: '経済状態・評価条件を変える', exact: true });
  await expect(panel.getByRole('button', { name: '乗数・税収・労働反応の条件', exact: true })).not.toBeVisible();
  await panel.getByText('詳細な条件', { exact: true }).click();
  await economyOpener.click();
  const economy = page.getByRole('dialog', { name: '経済状態・評価条件', exact: true });
  await expect(economy).toBeInViewport();
  await economy.getByLabel('潜在GDPギャップ（年0）・数値で入力', { exact: true }).fill('-2');
  await page.keyboard.press('Escape');
  await expect(economy).not.toBeVisible();
  await expect(economyOpener).toBeFocused();
  const opener = page.getByRole('button', { name: '乗数・税収・労働反応の条件', exact: true });
  await opener.click();
  const dialog = page.getByRole('dialog', { name: '乗数・税収・労働反応の条件', exact: true });
  await expect(dialog).toBeVisible();
  await expect(dialog.getByLabel('名目GDPに対する税収弾性値（税）・数値で入力', { exact: true })).toBeVisible();
  await dialog.getByLabel('名目GDPに対する税収弾性値（税）・数値で入力', { exact: true }).fill('1.7');
  await dialog.getByLabel('GDP乗数の感度倍率・数値で入力', { exact: true }).fill('1.5');
  await page.keyboard.press('Escape');
  await expect(dialog).not.toBeVisible();
  await expect(opener).toBeFocused();
  await expect.poll(headingTop).toBe(topBefore);
  await opener.click();
  await expect(dialog.getByLabel('GDP乗数の感度倍率・数値で入力', { exact: true })).toHaveValue('1.5');
  await expect(dialog.getByLabel('名目GDPに対する税収弾性値（税）・数値で入力', { exact: true })).toHaveValue('1.7');
  await dialog.getByRole('button', { name: '乗数・労働反応の設定を閉じる', exact: true }).click();
  const supplyOpener = page.getByRole('button', { name: '政策別の供給力・長期条件', exact: true });
  await supplyOpener.click();
  const supplyDialog = page.getByRole('dialog', { name: '政策別の供給力・長期条件', exact: true });
  await expect(supplyDialog).toBeVisible();
  await supplyDialog.locator('summary').filter({ hasText: /^公共資本の蓄積/ }).click();
  await supplyDialog.getByLabel('公共資本の蓄積・効果までの年数', { exact: true }).fill('4');
  await supplyDialog.getByRole('button', { name: '供給力・長期条件を閉じる', exact: true }).click();
  await expect(supplyOpener).toBeFocused();
  await page.getByRole('button', { name: /^政策パネルを閉じる/ }).first().click();
  await expect(panel).not.toBeVisible();
  await expect(heading).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'この条件のURLをコピー' }).click();
  const url = await page.getByLabel('共有URL', { exact: true }).inputValue();
  await page.goto(url);
  await page.getByRole('button', { name: /^政策を調整/ }).click();
  await economyOpener.click();
  await expect(economy.getByLabel('潜在GDPギャップ（年0）・数値で入力', { exact: true })).toHaveValue('-2');
  await economy.getByRole('button', { name: '経済状態・評価条件を閉じる', exact: true }).click();
  await opener.click();
  await expect(dialog.getByLabel('GDP乗数の感度倍率・数値で入力', { exact: true })).toHaveValue('1.5');
  await expect(dialog.getByLabel('名目GDPに対する税収弾性値（税）・数値で入力', { exact: true })).toHaveValue('1.7');
  await page.keyboard.press('Escape');
  await supplyOpener.click();
  await supplyDialog.locator('summary').filter({ hasText: /^公共資本の蓄積/ }).click();
  await expect(supplyDialog.getByLabel('公共資本の蓄積・効果までの年数', { exact: true })).toHaveValue('4');
});
